package com.taklifnoma.taklifnomalar.bot;

public enum BotState {
    START,
    AWAITING_TYPE,
    AWAITING_TEMPLATE,
    AWAITING_KUYOV_ISMI,
    AWAITING_KELIN_ISMI,
    AWAITING_MANZIL,
    AWAITING_LOCATION,
    AWAITING_AYOLLAR_TOSH,
    AWAITING_ERKAKLAR_TOSH,
    AWAITING_NIKOH_VAQTI,
    AWAITING_TUGILGAN_KUN_EGASI,
    AWAITING_YOSH,
    AWAITING_TADBIR_VAQTI,
    AWAITING_TABRIK_MATNI,
    AWAITING_PAYMENT,
    AWAITING_CONFIRMATION
}

